---
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports: [6379:6379]
    volumes: [./redis_data:/data]
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment: [REDIS_HOSTS=local:redis:6379]
    ports: [8081:8081]
  redis-insight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    restart: always
    ports: [5540:5540]
